build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      exists:
        - Dockerfile
  before_script:
    - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t abarchihiabdessamade/pitstop-gateway:1.0.0 .
    - docker push abarchihiabdessamade/pitstop-gateway:1.0.0