apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: cloudnative4/pitstop:pitstop-webapp
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: garage
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: http
    port: 8081
    targetPort: 80