apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: cloudnative4/pitstop:pitstop-express-gateway
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: customer
            value: "pitstop-customer-service"
          - name: vehicle
            value: "pitstop-vehicle-service"
          - name: workshop
            value: "pitstop-workshop-service"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: garage
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
